# DMC directory: "C:\Program Files\QSPICE\dm\bin\dmc.exe"
# DMC make directory: "C:\Program Files\QSPICE\dm\bin\make.exe"

pid_controller: ../../src/pid.c
	"C:\Program Files\QSPICE\dm\bin\dmc.exe" -mn -WD pid_controller.cpp kernel32.lib ../pid.c