# DMC directory: "C:\Program Files\QSPICE\dm\bin\dmc.exe"
# DMC make directory: "C:\Program Files\QSPICE\dm\bin\make.exe"

all: lpf_1st

lpf_1st: ../../src/filters.c
	"C:\Program Files\QSPICE\dm\bin\dmc.exe" -mn -WD lpf_1st.cpp kernel32.lib ../../src/filters.c